### PR TITLE
mint: allow for a NotImplemented response to multipartupload in aws-sdk-go

### PR DESCRIPTION
**Pull request by Fadila82**
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

### CODE REVIEW

**Review by ifraixedes — COMMENTED** [review]
I'm wondering if we should have a white list of functionalities that we expect to return `501` and if the functionality isn't in the list then report a fatal error as usual.

**Comment by Fadila82** [comment]
> I'm wondering if we should have a white list of functionalities that we expect to return `501` and if the functionality isn't in the list then report a fatal error as usual.

I'm not sure to understand what you mean. At which level the whitelist would be? Do you mean for all tests (something that would run the tests, check the errors, and then decide if it's really fatal from this whitelist? Or do you mean we should have this mechanism in each mint testsuite?

**Comment by ifraixedes** [comment]
> At which level the whitelist would be? Do you mean for all tests (something that would run the tests, check the errors, and then decide if it's really fatal from this whitelist? Or do you mean we should have this mechanism in each mint testsuite?

I don't mostly say where or how because I'm not familiar with this code; I'd say where it's easier to do it and more maintainable.

What I see is that if we don't check what functionality responds 501 then we can have false positives due that 501 is an acceptable response when in reality it isn't acceptable for the functionalities that we want to expose.

**Comment by Fadila82** [comment]
> > At which level the whitelist would be? Do you mean for all tests (something that would run the tests, check the errors, and then decide if it's really fatal from this whitelist? Or do you mean we should have this mechanism in each mint testsuite?
> 
> I don't mostly say where or how because I'm not familiar with this code; I'd say where it's easier to do it and more maintainable.
> 
> What I see is that if we don't check what functionality responds 501 then we can have false positives due that 501 is an acceptable response when in reality it isn't acceptable for the functionalities that we want to expose.

This check is only done in testListMultipartUploads only, when creating the multipart upload.

**Review by ifraixedes — APPROVED** [review]

**Pull request merged**
